import { SAFE_TEST_SCENARIOS, type DashboardMetricCard } from "../shared/platform";

export const MOCK_PLANS = [
  {
    id: 1,
    code: "starter-monthly",
    name: "Starter Monthly",
    tier: "starter",
    billingInterval: "monthly",
    currency: "USD",
    priceUsd: "49.00",
    includedRequests: 500,
    monthlyApiQuota: 500,
    monthlyBrowserRuns: 100,
    maxRpm: 30,
    maxConcurrentJobs: 1,
    vipApiAccess: "disabled",
    featuresJson: ["single-api", "dashboard", "basic-metrics"],
    isActive: "yes",
  },
  {
    id: 2,
    code: "vip-monthly",
    name: "VIP Monthly",
    tier: "vip",
    billingInterval: "monthly",
    currency: "USD",
    priceUsd: "299.00",
    includedRequests: 10000,
    monthlyApiQuota: 10000,
    monthlyBrowserRuns: 2500,
    maxRpm: 300,
    maxConcurrentJobs: 8,
    vipApiAccess: "enabled",
    featuresJson: ["single-api", "bulk-api", "vip-api", "priority-queue", "advanced-metrics"],
    isActive: "yes",
  },
];

export const MOCK_PROXY_PROVIDERS = [
  {
    id: 1,
    code: "evomi",
    name: "Evomi",
    protocolSupport: "http,socks5",
    sessionSupport: "rotating,sticky",
    costPerGbUsd: "2.4900",
    priority: 100,
    status: "healthy",
    notes: "Primary residential provider for default policy.",
    configJson: {
      supportsSticky: true,
      supportsRotating: true,
      supportsCountryRouting: true,
      defaultProtocol: "http",
    },
  },
  {
    id: 2,
    code: "dataimpulse",
    name: "DataImpulse",
    protocolSupport: "http,socks5",
    sessionSupport: "rotating,sticky",
    costPerGbUsd: "1.0000",
    priority: 120,
    status: "healthy",
    notes: "Lower-cost fallback provider for failover and cost optimization.",
    configJson: {
      supportsSticky: true,
      supportsRotating: true,
      supportsCountryRouting: true,
      defaultProtocol: "http",
    },
  },
];

export const MOCK_PROXY_POLICIES = [
  {
    id: 1,
    code: "default-rotating",
    name: "Default Rotating",
    protocol: "http",
    sessionMode: "rotating",
    stickyTtlMinutes: null,
    country: null,
    state: null,
    city: null,
    maxTransportRetries: 2,
    maxProviderSwitches: 1,
    costCeilingUsd: "0.5000",
    isDefault: "yes",
    policyJson: {
      providerOrder: ["evomi", "dataimpulse"],
      enableFallback: true,
      safeForBulk: true,
    },
  },
  {
    id: 2,
    code: "vip-sticky",
    name: "VIP Sticky 30m",
    protocol: "http",
    sessionMode: "sticky",
    stickyTtlMinutes: 30,
    country: "us",
    state: null,
    city: null,
    maxTransportRetries: 3,
    maxProviderSwitches: 2,
    costCeilingUsd: "2.0000",
    isDefault: "no",
    policyJson: {
      providerOrder: ["evomi", "dataimpulse"],
      enableFallback: true,
      sessionReuse: true,
    },
  },
];

export const MOCK_WORKER_NODES = [
  {
    id: 1,
    code: "worker-browser-a",
    name: "Browser Worker A",
    role: "browser",
    status: "healthy",
    concurrencyLimit: 4,
    activeJobs: 2,
    version: "0.1.0",
    hostLabel: "sandbox-local-a",
    lastHeartbeatAt: Date.now() - 15_000,
    capabilitiesJson: {
      safeTestBench: true,
      browserAutomation: true,
      camoufoxProfileMode: "simulated",
    },
  },
  {
    id: 2,
    code: "worker-api-b",
    name: "API Worker B",
    role: "hybrid",
    status: "healthy",
    concurrencyLimit: 8,
    activeJobs: 3,
    version: "0.1.0",
    hostLabel: "sandbox-local-b",
    lastHeartbeatAt: Date.now() - 8_000,
    capabilitiesJson: {
      safeTestBench: true,
      browserAutomation: false,
      apiBatching: true,
    },
  },
];

export const MOCK_JOBS = [
  {
    id: 1,
    publicId: "job_mock_success_001",
    userId: 1,
    apiKeyId: 1,
    source: "dashboard",
    requestMode: "single",
    status: "succeeded",
    queueName: "default",
    priority: 100,
    targetLabel: "mock://catalog/item/42",
    payloadJson: { target: "mock://catalog/item/42", action: "extract", safe: true },
    resultJson: {
      title: "Mock Catalog Item",
      price: 199.99,
      currency: "USD",
      oneCsResult: {
        creditScore: 742,
        productScore: 16,
        dataQualityScore: 8.5,
        adverseReasons: ["RiskView Consumer Inquiry"],
        adverseReasonGroups: ["inquiry_pressure"],
        status: "success",
        priceUsd: 1.9,
        durationMs: 18420,
        source: "dashboard",
        explanations: [
          "Raw credit score 742 mapped to product score 16/20.",
          "Record completeness contributed 86% of the available lead signals.",
          "Recent inquiry pressure added a smaller negative adjustment.",
          "Final status: success, data quality 8.5/10.",
        ],
        completenessScore: 0.86,
      },
      summary: {
        creditScore: 742,
        productScore: 16,
        dataQualityScore: 8.5,
        status: "success",
        adverseReasonCount: 1,
      },
    },
    errorCode: null,
    errorMessage: null,
    proxyPolicyId: 1,
    workerNodeId: 1,
    attemptCount: 1,
    maxAttempts: 3,
    costEstimateUsd: "0.0200",
    cogsUsd: "0.0110",
    createdAt: Date.now() - 3_600_000,
    startedAt: Date.now() - 3_540_000,
    completedAt: Date.now() - 3_520_000,
  },
  {
    id: 2,
    publicId: "job_mock_retry_002",
    userId: 1,
    apiKeyId: 1,
    source: "api",
    requestMode: "bulk",
    status: "waiting_retry",
    queueName: "bulk",
    priority: 120,
    targetLabel: "mock://retry/case",
    payloadJson: { target: "mock://retry/case", action: "extract", simulateRetryableError: true },
    resultJson: {
      oneCsResult: {
        creditScore: 611,
        productScore: 12,
        dataQualityScore: 3.5,
        adverseReasons: [
          "Income or credit history insufficient for loan",
          "Requested amount unsupported by income",
          "Too many accounts with balances",
        ],
        adverseReasonGroups: ["affordability", "utilization"],
        status: "decline",
        priceUsd: 1.7,
        durationMs: 26340,
        source: "api",
        explanations: [
          "Raw credit score 611 mapped to product score 12/20.",
          "Record completeness contributed 71% of the available lead signals.",
          "Income and debt affordability signals indicate lower financing readiness.",
          "High utilization or too many balances reduced quality despite other available signals.",
          "Final status: decline, data quality 3.5/10.",
        ],
        completenessScore: 0.71,
      },
      summary: {
        creditScore: 611,
        productScore: 12,
        dataQualityScore: 3.5,
        status: "decline",
        adverseReasonCount: 3,
      },
    },
    errorCode: "TRANSPORT_TIMEOUT",
    errorMessage: "First attempt timed out in safe test mode.",
    proxyPolicyId: 1,
    workerNodeId: 2,
    attemptCount: 1,
    maxAttempts: 3,
    costEstimateUsd: "0.1400",
    cogsUsd: "0.0320",
    createdAt: Date.now() - 1_800_000,
    startedAt: Date.now() - 1_790_000,
    completedAt: null,
  },
  {
    id: 3,
    publicId: "job_mock_vip_003",
    userId: 1,
    apiKeyId: 2,
    source: "testbench",
    requestMode: "vip",
    status: "running",
    queueName: "vip",
    priority: 10,
    targetLabel: "mock://provider/fallback",
    payloadJson: { target: "mock://provider/fallback", action: "extract", simulateProviderFailure: true },
    resultJson: {
      oneCsResult: {
        creditScore: 458,
        productScore: 6,
        dataQualityScore: 1,
        adverseReasons: [
          "Serious delinquency, and public record or collection filed",
          "High debt in relation to income",
        ],
        adverseReasonGroups: ["public_record", "affordability"],
        status: "decline",
        priceUsd: 2.5,
        durationMs: 28750,
        source: "testbench",
        explanations: [
          "Raw credit score 458 mapped to product score 6/20.",
          "Public record or collection signals materially reduced data quality.",
          "Income and debt affordability signals indicate lower financing readiness.",
          "Final status: decline, data quality 1/10.",
        ],
        completenessScore: 0.63,
      },
      summary: {
        creditScore: 458,
        productScore: 6,
        dataQualityScore: 1,
        status: "decline",
        adverseReasonCount: 2,
      },
    },
    errorCode: null,
    errorMessage: null,
    proxyPolicyId: 2,
    workerNodeId: 1,
    attemptCount: 1,
    maxAttempts: 4,
    costEstimateUsd: "0.3800",
    cogsUsd: "0.0900",
    createdAt: Date.now() - 600_000,
    startedAt: Date.now() - 580_000,
    completedAt: null,
  },
];

export const MOCK_JOB_EVENTS = [
  {
    id: 1,
    jobId: 1,
    eventType: "job.created",
    severity: "info",
    message: "Safe test job created from dashboard.",
    eventJson: { source: "dashboard" },
    createdAt: Date.now() - 3_600_000,
  },
  {
    id: 2,
    jobId: 1,
    eventType: "worker.completed",
    severity: "info",
    message: "Worker finished safe extraction flow.",
    eventJson: { runtimeMs: 20000, proxyProvider: "evomi" },
    createdAt: Date.now() - 3_520_000,
  },
  {
    id: 3,
    jobId: 2,
    eventType: "proxy.transport_timeout",
    severity: "warn",
    message: "Retryable transport timeout detected on first attempt.",
    eventJson: { provider: "evomi", retryable: true },
    createdAt: Date.now() - 1_780_000,
  },
  {
    id: 4,
    jobId: 2,
    eventType: "job.waiting_retry",
    severity: "warn",
    message: "Job returned to queue with exponential backoff.",
    eventJson: { backoffMs: 30000 },
    createdAt: Date.now() - 1_775_000,
  },
  {
    id: 5,
    jobId: 3,
    eventType: "proxy.provider_fallback",
    severity: "warn",
    message: "Primary provider degraded, fallback lease simulation activated.",
    eventJson: { from: "evomi", to: "dataimpulse" },
    createdAt: Date.now() - 560_000,
  },
];

export const MOCK_AUDIT_TRAIL = [
  {
    id: 1,
    actorUserId: 1,
    actorType: "user",
    action: "job.create",
    resourceType: "job",
    resourceId: "job_mock_success_001",
    status: "success",
    ipAddress: "127.0.0.1",
    detailsJson: { mode: "single", source: "dashboard" },
    createdAt: Date.now() - 3_600_000,
  },
  {
    id: 2,
    actorUserId: 1,
    actorType: "user",
    action: "apikey.create",
    resourceType: "api_key",
    resourceId: "key_mock_vip_002",
    status: "success",
    ipAddress: "127.0.0.1",
    detailsJson: { scope: "vip" },
    createdAt: Date.now() - 7_200_000,
  },
  {
    id: 3,
    actorUserId: null,
    actorType: "system",
    action: "proxy.fallback",
    resourceType: "job",
    resourceId: "job_mock_vip_003",
    status: "success",
    ipAddress: null,
    detailsJson: { from: "evomi", to: "dataimpulse" },
    createdAt: Date.now() - 560_000,
  },
];

export const MOCK_METRIC_CARDS: DashboardMetricCard[] = [
  {
    key: "success_rate",
    title: "Success Rate",
    value: "98.4%",
    delta: "+1.2% vs 24h",
    status: "good",
  },
  {
    key: "queue_depth",
    title: "Queue Depth",
    value: "12",
    delta: "3 VIP / 4 bulk / 5 default",
    status: "neutral",
  },
  {
    key: "proxy_cogs",
    title: "Proxy COGS",
    value: "$184.42",
    delta: "-6.8% vs 24h",
    status: "good",
  },
  {
    key: "transport_errors",
    title: "Transport Errors",
    value: "7",
    delta: "2 retryable / 5 resolved",
    status: "warn",
  },
];

export const MOCK_USAGE_SUMMARY = {
  currentPeriod: "2026-04",
  requests: 6240,
  browserRuns: 980,
  proxyTrafficGb: 182.42,
  cogsUsd: 184.42,
  revenueUsd: 622.15,
  marginUsd: 437.73,
};

export const MOCK_HEALTH_SUMMARY = {
  status: "healthy",
  queues: {
    default: { depth: 5, lagSeconds: 12 },
    bulk: { depth: 4, lagSeconds: 28 },
    vip: { depth: 3, lagSeconds: 6 },
  },
  providers: {
    evomi: { status: "healthy", successRate: 0.981, avgLeaseMs: 320 },
    dataimpulse: { status: "healthy", successRate: 0.974, avgLeaseMs: 410 },
  },
  workers: {
    total: MOCK_WORKER_NODES.length,
    healthy: MOCK_WORKER_NODES.filter(worker => worker.status === "healthy").length,
  },
};

export const MOCK_API_KEYS = [
  {
    id: 1,
    userId: 1,
    label: "Primary Single/Bulk Key",
    keyPrefix: "cs_live_01",
    scope: "bulk",
    status: "active",
    rpmLimit: 120,
    dailyLimit: 5000,
    lastUsedAt: Date.now() - 300_000,
    expiresAt: null,
  },
  {
    id: 2,
    userId: 1,
    label: "VIP Partner Key",
    keyPrefix: "cs_vip_02",
    scope: "vip",
    status: "active",
    rpmLimit: 300,
    dailyLimit: 25000,
    lastUsedAt: Date.now() - 45_000,
    expiresAt: null,
  },
];

export const MOCK_SUBSCRIPTIONS = [
  {
    id: 1,
    userId: 1,
    planId: 2,
    status: "active",
    provider: "manual",
    externalRef: "sub_mock_001",
    startedAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    currentPeriodStart: Date.now() - 2 * 24 * 60 * 60 * 1000,
    currentPeriodEnd: Date.now() + 28 * 24 * 60 * 60 * 1000,
  },
];

export const MOCK_PAYMENTS = [
  {
    id: 1,
    userId: 1,
    subscriptionId: 1,
    provider: "manual",
    status: "confirmed",
    currency: "USD",
    amount: "299.00",
    amountUsd: "299.00",
    txRef: "manual-recon-001",
    invoiceRef: "vip-monthly-2026-04",
    paidAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
];

export function getMockDashboardSummary() {
  return {
    metrics: MOCK_METRIC_CARDS,
    jobs: MOCK_JOBS,
    providers: MOCK_PROXY_PROVIDERS,
    workers: MOCK_WORKER_NODES,
    usage: MOCK_USAGE_SUMMARY,
    safeTestScenarios: SAFE_TEST_SCENARIOS,
    health: MOCK_HEALTH_SUMMARY,
  };
}

export function findMockJob(publicId: string) {
  return MOCK_JOBS.find(job => job.publicId === publicId) ?? null;
}

export function listMockJobEvents(jobId: number) {
  return MOCK_JOB_EVENTS.filter(event => event.jobId === jobId)
    .map(event => ({
      ...event,
      createdAt: new Date(event.createdAt),
    }))
    .sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime());
}

export function listMockAuditTrail() {
  return MOCK_AUDIT_TRAIL.map(entry => ({
    id: entry.id,
    actorUserId: entry.actorUserId ?? null,
    actorType: entry.actorType,
    action: entry.action,
    resourceType: entry.resourceType,
    resourceId: entry.resourceId,
    status: entry.status,
    ipAddress: entry.ipAddress ?? null,
    detailsJson: entry.detailsJson,
    createdAt: new Date(entry.createdAt),
  })).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}
