"""
Spanish button texts for Mirror Bot
Fallbacks inherit from English when not overridden.
"""

from mirror_bot.constants.buttons_en import ButtonTexts as EnglishButtonTexts


class ButtonTexts(EnglishButtonTexts):
    LANG_RUSSIAN = "🇷🇺 Ruso"
    LANG_ENGLISH = "🇬🇧 Inglés"
    LANG_CHINESE = "🇨🇳 Chino"
    LANG_SPANISH = "🇪🇸 Español"

    SEND_MONEY = "💸 Enviar dinero a otro usuario"
    REFERRAL_SYSTEM = "🤝 Sistema de referidos"
    MY_BANK_ORDERS = "📦 Mis pedidos bancarios"
    MY_PURCHASES = "📦 Mis compras"
    SETUP_ARCHIVE = "📁 Configurar archivo"
    CHOOSE_LANGUAGE = "🌍 Elegir idioma"
    BACK = "⬅️ Atrás"

    PAY_VIA_CRYPTOBOT = "🪙 Pagar vía CryptoBot"
    PAY_VIA_CRYPTOMUS = "💎 Pagar vía Cryptomus"
    OPEN_PAYMENT_LINK = "💳 Abrir enlace de pago"
    REFRESH_STATUS = "♻️ Actualizar estado"
    CANCEL = "❌ Cancelar"
    BACK_TO_MENU = "⬅️ Volver al menú"

    CONFIRM = "✅ Confirmar"
    EDIT = "✏️ Editar"
    CONTINUE = "✅ Continuar"
    CONFIRM_PAY = "✅ Confirmar y pagar"

    SUPPORT_PAYMENT = "💰 Depósito"
    SUPPORT_PRODUCT = "📦 Producto"
    SUPPORT_GENERAL = "💬 General"
    SUPPORT_PARTNERSHIP = "🤝 Colaboración"
    MY_TICKETS = "📋 Mis tickets"
    SUPPORT_BACK = "⬅️ Atrás"

    TICKET_REPLY = "✍️ Responder"
    TICKET_ATTACH_FILES = "📎 Adjuntar archivos"
    TICKET_BACK_TO_TICKETS = "⬅️ Volver a mis tickets"
    TICKET_BACK_TO_SUPPORT = "⬅️ Volver a soporte"

    EDUCATION = "📚 Educación"
    MY_PROFILE = "👤 Mi perfil"
    TOP_UP_BALANCE = "💳 Recargar saldo"
    SEARCH = "🔎 Búsqueda"
    CREDIT_REPORTS = "📈 REPORTES DE CRÉDITO"
    DOCUMENTS = "📄 DOCUMENTOS"
    PROS_FULLZ = "🧰 PROS Y FULLZ"
    BANKS = "🏦 BANCOS"
    CC = "💳 CC"
    NFC = "📱 NFC"
    ENROLL = "🏦 Enroll"

    # ========== CC ==========
    CC_BUY = "🛒 Comprar"
    CC_LIKE = "👍 Me gusta"
    CC_DISLIKE = "👎 No me gusta"
    CC_REPORT_ISSUE = "⚠️ Reportar problema"
    CC_BACK_TO_CC = "⬅️ Volver a CC"
    CC_OPEN_CHAT = "💬 Abrir chat con vendedor"
    CC_NO_ITEMS = "📭 Sin artículos disponibles"
    SELFREG_BA = "🏧 Selfreg BA"
    LOGS = "📋 Logs"
    OTP_CARD = "📲 OTP Card"
    SELFREG_CC = "💳 Selfreg CC"
    CHECKS = "📄 Checks"
    ESIM = "📶 eSIM"
    SUBSCRIPTIONS_ACCOUNTS = "🧾 Suscripciones / Cuentas"
    ADD_INFO_CR = "✍️ Añadir info en CR"
    SERVICE_RULES = "📜 Reglas del servicio"
    CALL_SERVICE = "📞 CONTACTAR SERVICIO"
    ANOTHER_SERVICES = "📞 Otros servicios"
    REFERRALS = "🤝 Referidos +25%"
    SUPPORT = "📞 Soporte"
    ACCEPT_RULES = "✅ Acepto las reglas"
    DECLINE_RULES = "❌ No acepto"
    VIEW_RULES = "📜 Reglas"

    PREV = "⬅️ Anterior"
    NEXT = "Siguiente ➡️"
    PREV_PAGE = "⬅️ Anterior"
    NEXT_PAGE = "Siguiente ➡️"
    BACK_SUPPORT = "⬅️ Atrás"
    BACK_TO_SUPPORT = "⬅️ Volver a soporte"
    BACK_TO_CATEGORIES = "🏠 Volver a categorías"
