# ========== NOTIFICATION TEXTS ==========
ORDER_COMPLETED_BULK_ITEM = "✅ 您的订单 #{order_id} 项目 #{item_number} 已完成！"
ORDER_COMPLETED_SINGLE = "✅ 您的订单 #{order_id} 已完成！"
ORDER_NOT_FOUND_BULK_ITEM = "❌ 您的订单 #{order_id} 项目 #{item_number} - 未找到"
ORDER_NOT_FOUND_SINGLE = "❌ 您的订单 #{order_id} - 未找到"
BULK_ORDER_COMPLETED = "🎯 您的批量订单 #{order_id} 已完成！"

ORDER_DETAILS = "📋 订单详情："
SERVICE_TEXT = "服务："
STATUS_TEXT = "状态："
ITEM_TEXT = "项目："
FILES_TEXT = "文件："
BALANCE_TEXT = "余额："
REFUND_TEXT = "退款："
RESULT_READY = "您的项目 #{item_number} 结果已准备好！🎉"
ORDER_COMPLETE_THANKS = "您的订单已完成！感谢使用我们的服务！🎉"
NOT_FOUND_MESSAGE = "很抱歉，我们无法找到此项目的信息。\n您的款项已自动退还。💸"
REFUND_PROCESSED = "很抱歉，我们无法找到所请求的信息。\n您的款项已自动退还。💸"

FINAL_RESULTS = "📊 最终结果："
ITEMS_FOUND_DELIVERED = "找到并交付："
ITEMS_NOT_FOUND_REFUNDED = "未找到（已退款）："
SUMMARY_TEXT = "💰 总结："
ITEMS_FOUND = "找到的项目："
ITEMS_REFUNDED = "退款的项目："
CHECK_CHAT_HISTORY = "所有单独的结果已在上方发送。请查看聊天记录以获取每个项目的详细信息和文件。"
CURRENT_BALANCE = "您的当前余额："
THANK_YOU = "感谢您的订单！🙏"
