class ButtonTexts:
    ACCEPT_RULES = "✅ Accept"
    DECLINE_RULES = "❌ Decline"
    MY_BANKS = "🏦 My Banks"
    ADD_BANK = "➕ Add Bank"
    MY_UPLOADS = "🗂 My Uploads"
    MY_CC = "💳 My CC Items"
    ADD_CC = "➕ Add CC Item"
    BRUTE_BANK = "🔓 Brute Bank"
    MY_ORDERS = "📦 My Orders"
    MESSAGES = "💬 Messages"
    MINI_APP = "🖥 Mini App"
    WITHDRAW = "💸 Withdraw"
    PROFILE = "👤 Profile"

    # ── Documents ──────────────────────────────────
    MY_DOCS = "📄 My Documents"
    ADD_DOC = "➕ Add Document"
    DOC_TYPE_DL = "🪪 Driver's License (Front+Back)"
    DOC_TYPE_DL_SELFIE = "🤳 Driver's License + Selfie"
    DOC_TYPE_PASSPORT = "🛂 Passport"
    DOC_TYPE_BUSINESS = "🏢 Business Docs"
    DOC_QUALITY_STANDARD = "⭐ Standard"
    DOC_QUALITY_PREMIUM = "💎 Premium"

    # ── Fullz ──────────────────────────────────────
    MY_FULLZ = "🧑‍💼 My Fullz"
    ADD_FULLZ = "➕ Add Fullz"
    FULLZ_TYPE_PERSONAL = "👤 Personal"
    FULLZ_TYPE_BUSINESS = "🏢 Business"
    FULLZ_CS_ANY = "🔘 Any CS — $0"
    FULLZ_CS_500 = "💠 500+"
    FULLZ_CS_700 = "✨ 700+"
    FULLZ_CS_800 = "⭐ 800+"
    FULLZ_AGE_ANY = "🎲 Any Age — $0"
    FULLZ_AGE_18 = "🧒 18–25"
    FULLZ_AGE_26 = "👨 26–35"
    FULLZ_AGE_36 = "🧓 36+"
    FULLZ_GENDER_ANY = "🎲 Any Gender — $0"
    FULLZ_GENDER_MALE = "👨 Male"
    FULLZ_GENDER_FEMALE = "👩 Female"
    FULLZ_COMPANY_SOLE = "👤 Sole Proprietor"
    FULLZ_COMPANY_LLC = "🏢 LLC"
    FULLZ_COMPANY_CORP = "🏛️ Corp"
    FULLZ_LOAN_ANY = "📊 Any Loan — $0"
    FULLZ_LOAN_25_200 = "💰 $25k–$200k"
    FULLZ_LOAN_200_500 = "💰 $200k–$500k"
    FULLZ_LOAN_500_PLUS = "💰 $500k+"
    FULLZ_REPORT_BASIC = "💼 Basic"
    FULLZ_REPORT_CR = "📘 With CR"
    FULLZ_REPORT_CR_DL = "🪪 CR & DL"
    FULLZ_REPORT_CR_DL_MVR = "🛰️ CR, DL & MVR"
    FULLZ_REPORT_FULL = "🏁 CR, DL & FULL MVR"
