from seller_bot.constants.buttons_en import ButtonTexts as EnglishButtonTexts


class ButtonTexts(EnglishButtonTexts):
    ACCEPT_RULES = "✅ Принимаю"
    DECLINE_RULES = "❌ Отклоняю"
    MY_BANKS = "🏦 Мои банки"
    ADD_BANK = "➕ Добавить банк"
    MY_UPLOADS = "🗂 Мои загрузки"
    MY_CC = "💳 Мои CC"
    ADD_CC = "➕ Добавить CC"
    BRUTE_BANK = "🔓 Brute Bank"
    MY_ORDERS = "📦 Мои заказы"
    MESSAGES = "💬 Сообщения"
    MINI_APP = "🖥 Mini App"
    WITHDRAW = "💸 Вывод"
    PROFILE = "👤 Профиль"

    # ── Documents ──────────────────────────────────
    MY_DOCS = "📄 Мои документы"
    ADD_DOC = "➕ Добавить документ"
    DOC_TYPE_DL = "🪪 Права (Перед+Зад)"
    DOC_TYPE_DL_SELFIE = "🤳 Права + Селфи"
    DOC_TYPE_PASSPORT = "🛂 Паспорт"
    DOC_TYPE_BUSINESS = "🏢 Бизнес-документы"
    DOC_QUALITY_STANDARD = "⭐ Стандарт"
    DOC_QUALITY_PREMIUM = "💎 Премиум"

    # ── Fullz ──────────────────────────────────────
    MY_FULLZ = "🧑‍💼 Мои Fullz"
    ADD_FULLZ = "➕ Добавить Fullz"
    FULLZ_TYPE_PERSONAL = "👤 Персональный"
    FULLZ_TYPE_BUSINESS = "🏢 Бизнес"
    FULLZ_CS_ANY = "🔘 Любой КС — $0"
    FULLZ_CS_500 = "💠 500+"
    FULLZ_CS_700 = "✨ 700+"
    FULLZ_CS_800 = "⭐ 800+"
    FULLZ_AGE_ANY = "🎲 Любой возраст — $0"
    FULLZ_AGE_18 = "🧒 18–25"
    FULLZ_AGE_26 = "👨 26–35"
    FULLZ_AGE_36 = "🧓 36+"
    FULLZ_GENDER_ANY = "🎲 Любой пол — $0"
    FULLZ_GENDER_MALE = "👨 Мужской"
    FULLZ_GENDER_FEMALE = "👩 Женский"
    FULLZ_COMPANY_SOLE = "👤 ИП (Sole Proprietor)"
    FULLZ_COMPANY_LLC = "🏢 LLC"
    FULLZ_COMPANY_CORP = "🏛️ Corp"
    FULLZ_LOAN_ANY = "📊 Любой размер — $0"
    FULLZ_LOAN_25_200 = "💰 $25k–$200k"
    FULLZ_LOAN_200_500 = "💰 $200k–$500k"
    FULLZ_LOAN_500_PLUS = "💰 $500k+"
    FULLZ_REPORT_BASIC = "💼 Базовый"
    FULLZ_REPORT_CR = "📘 С CR"
    FULLZ_REPORT_CR_DL = "🪪 CR и DL"
    FULLZ_REPORT_CR_DL_MVR = "🛰️ CR, DL и MVR"
    FULLZ_REPORT_FULL = "🏁 CR, DL и FULL MVR"
