class BotTexts:
    CHOOSE_LANGUAGE = "🌍 <b>Choose your language</b>\n\nSelect the language for the seller panel:"
    RULES_TEXT = (
        "📋 <b>Seller Rules</b>\n\n"
        "Before access is granted, you must accept the seller rules.\n\n"
        "💰 <b>Deposit explanation</b>\n"
        "Banks: <b>$100</b>\n"
        "CC: <b>$50</b>\n\n"
        "This is a security deposit, not a fee. The money stays on your seller balance and can be withdrawn later. "
        "It is used as a quality guarantee and dispute coverage.\n\n"
        "Press <b>Accept</b> to submit your seller application."
    )
    RULES_DECLINED = "❌ You declined the seller rules. Seller access was not requested."
    WELCOME_BACK = "👋 Welcome back, <b>{name}</b>!\n\n🏦 Your seller panel is ready.\n📦 Total orders: {total_orders}\n💰 Total earned: ${total_earned:.2f}"
    PENDING_APPROVAL = "⏳ <b>Your application is pending approval.</b>\n\nPlease wait for the admin to review your request.\nYou will be notified when your account is approved."
    START_NEW = "🏦 <b>Seller Bot</b>\n\nWelcome! This bot allows you to sell bank accounts.\n\nStart by choosing your language and accepting the seller rules."
    ALREADY_REGISTERED = "✅ You are already registered as a seller!"
    ALREADY_PENDING = "⏳ Your application is already pending approval."
    APPLICATION_SUBMITTED = "✅ <b>Application submitted!</b>\n\nYour seller application has been sent to the admin.\nYou will be notified when it's approved."
    APPLICATION_APPROVED = "🎉 <b>Your seller account has been approved!</b>\n\nYou can now add products and receive orders.\nSend /start to open your seller panel."
    MENU_TEXT = "🏦 <b>Seller Panel</b>\n\n👤 {name}\n📦 Orders: {total_orders}\n💰 Earned: ${total_earned:.2f}"
    NO_SELLER_ACCESS = "❌ You don't have seller access."
    PROFILE_TEXT = "👤 <b>Seller Profile</b>\n\n📛 Name: <b>{name}</b>\n📱 Username: @{username}\n🏷 Type: {seller_type}\n📊 Markup: {markup}%\n\n🏦 <b>Banks:</b>\n   Total: {total_banks}\n   In Stock: {in_stock_banks}\n\n📦 <b>Orders:</b>\n   Active: {active_orders}\n   Completed: {completed_orders}\n   Total: {total_orders}\n\n💰 Total earned: <b>${total_earned:.2f}</b>\n💵 Legacy settled balance: <b>${deposit:.2f}</b>\n🟡 Pending balance: <b>${pending:.2f}</b>\n🟢 Withdrawable balance: <b>${withdrawable:.2f}</b>\n📅 Registered: {registered}"
    NOT_AUTHORIZED = "❌ Not authorized"
    WITHDRAW_INSUFFICIENT = "Insufficient balance"
    WITHDRAW_START = "💸 <b>Withdraw Funds</b>\n\nAvailable to withdraw: <b>${withdrawable:.2f}</b>\nPending settlement: <b>${pending:.2f}</b>\n\nEnter the amount to withdraw (USD):"
    WITHDRAW_ENTER_VALID = "Please enter a valid number (e.g. 50 or 100.50)"
    WITHDRAW_POSITIVE = "Amount must be positive."
    WITHDRAW_NOT_ENOUGH = "Insufficient balance. You have ${balance:.2f}"
    WITHDRAW_ENTER_DETAILS = "Enter your wallet/payment details (card, crypto address, etc.):"
    WITHDRAW_CANCELLED = "Insufficient balance. Request cancelled."
    WITHDRAW_CREATED = "✅ Withdrawal request created!\n\nAmount: ${amount:.2f}\nStatus: Pending admin approval\n\nYou will be notified when it is processed."
